on:
  workflow_call:
    inputs:
      should_skip:
        required: true
        type: string

jobs:
  build:
    if: ${{ inputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
